### ISSUE TITLE
Master stations do not appear in the log

### ISSUE THREAD

**Issue by denisfrench** [OpenSprinkler/OpenSprinklerGen2#15]
The log shows a row for the master station, but never actually logs when it has been turned on.

I use a mix of stations that do and do not run with the master, so logging when the master is on would be helpful.

**Comment by rayshobby** [comment]
This is not a bug -- the master station is not logged. First of all, this is because master station is not an active station -- it's only activated when other stations are on, so in a sense it can't operate on its own. Second, the way master is implemented is different from other stations, so to log it requires a bit more coding. It's certainly possible, I just haven't though it's necessary.
