### ISSUE TITLE
Save and Restore settings as part of firmware upgrade

### ISSUE THREAD

**Issue by rhldr** [OpenSprinkler/OpenSprinklerGen2#22]
Is it possible to add support for saving and restoring settings as part of the updater application?

**Comment by salbahra** [comment]
We are exploring this option after the forum feedback however there are some issues preventing this at the moment.

First, using the current Javascript in the app to pull the JSON using the network isn't possible in most cases since people move the controller to plug it in via USB (disconnecting the Ethernet cable). Therefore, having a hidden app instance run and parse the data and reimport it after really isn't possible.

Second, the firmware doesn't have a mechanism to communicate with the firmware updater at the moment. This is something we can possibly build out and will look into it.

Thanks!
